### PR TITLE
In which I get a very basic ui started

### PR DESCRIPTION
**Pull request by natis1**

### CODE REVIEW

**Comment by port19x** [comment]
I'll take a look at it

**Comment by ura43** [comment]
And yeah, gplv3 coming...

**Review by port19x — APPROVED** [review]
Oh, you took care of the License already. Thanks

**Review by port19x — APPROVED** [review]
Haven't fully wrapped my head around PyQt5 yet, but judging by the screenshots you sent on discord this is a very good starting place

**Comment by ralf1307** [comment]
Merged to new Branch /dev.

Closing!

**Pull request closed without merging**
